### ISSUE TITLE
libxml++-3.0

### ISSUE THREAD

**Issue by rezso** [subtitleeditor/subtitleeditor#1]
Build with libxml++-3.0 fails:

isocodes.cc: In function 'bool isocodes::iso_codes_load_file(const Glib::ustring&, const Glib::ustring&, std::map<Glib::ustring, Glib::ustring>&)':
isocodes.cc:51:53: error: conversion from 'xmlpp::Node::const_NodeList {aka std::__cxx11::list<const xmlpp::Node*>}' to non-scalar type 'xmlpp::Node::NodeList {aka std::__cxx11::listxmlpp::Node*}' requested
   xmlpp::Node::NodeList entries =
   root->get_children(Glib::ustring::compose("%1_entry", iso_id));

After removing iso-codes from build depends, the build fails again with
similar error:

patternmanager.cc: In member function 'void PatternManager::load_pattern(const Glib::ustring&, const Glib::ustring&)':
patternmanager.cc:127:70: error: conversion from 'xmlpp::Node::const_NodeList {aka std::__cxx11::list<const xmlpp::Node*>}' to non-scalar type 'xmlpp::Node::NodeList {aka std::__cxx11::listxmlpp::Node*}' requested
   xmlpp::Node::NodeList xml_pattern_list = xml_patterns->get_children("pattern");

patternmanager.cc: In member function 'Pattern\* PatternManager::read_pattern(const xmlpp::Element_)':
patternmanager.cc:178:65: error: conversion from 'xmlpp::Node::const_NodeList {aka std::__cxx11::list<const xmlpp::Node_>}' to non-scalar type 'xmlpp::Node::NodeList {aka std::__cxx11::listxmlpp::Node*}' requested
  xmlpp::Node::NodeList xml_rule_list = xml_pattern->get_children("rule");

patternmanager.cc:196:69: error: conversion from 'xmlpp::Node::const_NodeList {aka std::__cxx11::list<const xmlpp::Node*>}' to non-scalar type 'xmlpp::Node::NodeList {aka std::__cxx11::listxmlpp::Node*}' requested
    xmlpp::Node::NodeList xml_previous_match = xml_rule->get_children("previousmatch");

**Comment by rezso** [comment]
Hello, sorry for the late reply. I use a very small distribution. 9 years ago, only 3 sources required libxml++. One of them were 3.0. It's not always a good idea to have multiple versions of the same lib (see ffmpeg), so I settled on 3.0. I think it's easier to switch from 2.6 to 3.0 than the other way around. And it wasn't difficult.
